#!/usr/bin/env tsx
/**
 * Evolution harness. Triggered by feedback_daemon once vote_counter reaches
 * EVOLUTION_TRIGGER_VOTES. Invokes reflect_evolve, collects the proposed
 * edits to reflect.md / reflect_light.md, commits to meta/evolution, and
 * populates inbox/evolution/ for the user to approve/reject.
 *
 * No A/B on evolution — user reads RATIONALE + diff and votes on
 * plausibility. If the agent returns without a diff (valid "tie-goes-to-old"
 * meta² null result), write a SKIP.md note and reset the vote counter.
 *
 * Shared setup/teardown (lock, worktree, cleanup) is in withMetaWorktree.
 *
 * Usage:
 *   tsx scripts/evolve_harness.mts <sisyphus-root>
 */

import { spawnSync } from "node:child_process";
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { resetVoteCounter, EVOLUTION_BRANCH } from "../src/meta-agents/state.js";
import { git, deleteBranchIfExists } from "../src/meta-agents/git-helpers.js";
import { withMetaWorktree } from "../src/meta-agents/harness-helpers.js";

const [, , sisyphusRoot] = process.argv;
if (!sisyphusRoot) {
  console.error("usage: evolve_harness.mts <sisyphus-root>");
  process.exit(2);
}

const result = await withMetaWorktree(
  sisyphusRoot,
  { lockOwner: "evolve_harness", worktreePrefix: "sisyphus-evolve-" },
  async (worktree, paths) => {
    const vars = {
      SISYPHUS_ROOT: worktree,
      META_STATE_DIR: paths.stateDir,
      INBOX_DIR: paths.inboxDir,
    };

    console.error(`[evolve_harness] invoking reflect_evolve in ${worktree}`);
    const r = spawnSync(
      "npx",
      [
        "tsx",
        join(sisyphusRoot, "scripts/invoke_meta_agent.mts"),
        "reflect_evolve",
        worktree,
        JSON.stringify(vars),
        "Meta² self-evolution. Review reflect's last 10 proposals + votes, propose edits to reflect.md / reflect_light.md if warranted.",
      ],
      { stdio: "inherit", cwd: sisyphusRoot },
    );
    if (r.status !== 0) throw new Error(`reflect_evolve exited ${r.status}`);

    const diff = git(worktree, "status", "--porcelain", "src/meta-agents/definitions");
    if (diff.trim().length === 0) {
      console.error(`[evolve_harness] agent returned no changes (valid "tie-goes-to-old" meta²) — resetting counter`);
      resetVoteCounter();
      mkdirSync(paths.inboxEvolution, { recursive: true });
      writeFileSync(
        join(paths.inboxEvolution, "SKIP.md"),
        `Evolution cycle @ ${new Date().toISOString()}: reflect_evolve reviewed 10 votes and proposed no changes.\n`,
      );
      return;
    }

    git(worktree, "add", "-A", "src/meta-agents/definitions");
    deleteBranchIfExists(sisyphusRoot, EVOLUTION_BRANCH);
    git(worktree, "checkout", "-B", EVOLUTION_BRANCH);
    git(worktree, "commit", "-m", "reflect_evolve: meta-agent prompt update", "-m", `autogenerated @ ${new Date().toISOString()}`);

    const diffText = git(sisyphusRoot, "diff", "main", EVOLUTION_BRANCH, "--", "src/meta-agents/definitions");
    mkdirSync(paths.inboxEvolution, { recursive: true });
    writeFileSync(join(paths.inboxEvolution, "diff.txt"), diffText);

    if (!existsSync(join(paths.inboxEvolution, "RATIONALE.md"))) {
      writeFileSync(
        join(paths.inboxEvolution, "RATIONALE.md"),
        `# Missing rationale\n\nreflect_evolve produced a diff but did not write RATIONALE.md. Read diff.txt and decide.\n`,
      );
    }

    writeFileSync(
      join(paths.inboxEvolution, "VOTE.md"),
      `# Evolution Vote\n\nRead RATIONALE.md and diff.txt in this folder. Write your choice below on a line starting with "choice:".\n\n` +
      `choice: \n\n` +
      `(valid values: \`approve\`, \`reject\`. Daemon will merge meta/evolution into main if approve, delete the branch if reject.)\n`,
    );

    console.error(`[evolve_harness] done. Inbox evolution at ${paths.inboxEvolution}`);
  },
);

if (result.status === "lock_conflict") {
  console.error("[evolve_harness] inbox locked — abort evolution");
  process.exit(0);
}
