#!/usr/bin/env tsx
/**
 * Deep-review harness. Orchestrates:
 *   1. create detached worktree from main
 *   2. invoke reflect agent inside it (may edit src/agents/definitions/*.md)
 *   3. if working-tree diff: force-update meta/pending branch + trigger A/B
 *   4. if no diff: evidence-only (agent saved PROPOSAL.md, no A/B rerun)
 *   5. ensure VOTE.md template exists in the inbox
 *   6. rotate observations.jsonl / support.jsonl + reset run_counter
 *
 * Shared setup/teardown (lock, worktree, cleanup) is in withMetaWorktree.
 *
 * Usage:
 *   tsx scripts/reflect_harness.mts <sisyphus-root>
 */

import { spawnSync } from "node:child_process";
import { existsSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import {
  resetRunCounter,
  rotateObservationLogs,
  PENDING_BRANCH,
} from "../src/meta-agents/state.js";
import { git, deleteBranchIfExists } from "../src/meta-agents/git-helpers.js";
import { withMetaWorktree } from "../src/meta-agents/harness-helpers.js";

const [, , sisyphusRoot] = process.argv;
if (!sisyphusRoot) {
  console.error("usage: reflect_harness.mts <sisyphus-root>");
  process.exit(2);
}

const result = await withMetaWorktree(
  sisyphusRoot,
  { lockOwner: "reflect_harness", worktreePrefix: "sisyphus-reflect-" },
  async (worktree, paths) => {
    const deepVars = {
      SISYPHUS_ROOT: worktree,
      META_STATE_DIR: paths.stateDir,
      INBOX_DIR: paths.inboxDir,
    };

    console.error(`[reflect_harness] invoking reflect in ${worktree}`);
    const reflectRes = spawnSync(
      "npx",
      [
        "tsx",
        join(sisyphusRoot, "scripts/invoke_meta_agent.mts"),
        "reflect",
        worktree,
        JSON.stringify(deepVars),
        "Deep review. Consolidate accumulated observations; update rolling pending; edit src/agents/definitions/*.md in this worktree if the diff should change.",
      ],
      { stdio: "inherit", cwd: sisyphusRoot },
    );
    if (reflectRes.status !== 0) {
      throw new Error(`reflect agent failed with status ${reflectRes.status}`);
    }

    // Reflect consumed the observations. Rotate + reset NOW, not at the tail
    // of the success path: if A/B throws below, we still want counter cleared
    // so we don't re-invoke this (expensive opus) agent on every next session.
    rotateObservationLogs();
    resetRunCounter();

    const diff = git(worktree, "status", "--porcelain", "src/agents/definitions", "skills");
    const hasDiff = diff.trim().length > 0;
    console.error(`[reflect_harness] working-tree diff: ${hasDiff ? "yes" : "no"}`);

    if (!hasDiff) {
      console.error("[reflect_harness] evidence-only update, PROPOSAL.md saved by agent. skipping A/B.");
      return;
    }

    git(worktree, "add", "-A", "src/agents/definitions", "skills");
    deleteBranchIfExists(sisyphusRoot, PENDING_BRANCH);
    git(worktree, "checkout", "-B", PENDING_BRANCH);
    git(worktree, "commit", "-m", "reflect: deep-review proposal", "-m", `autogenerated @ ${new Date().toISOString()}`);

    console.error(`[reflect_harness] triggering A/B`);
    const abRes = spawnSync(
      "npx",
      ["tsx", join(sisyphusRoot, "scripts/reflect_ab.mts"), sisyphusRoot, PENDING_BRANCH],
      { stdio: "inherit", cwd: sisyphusRoot },
    );
    if (abRes.status !== 0) {
      throw new Error(`A/B run failed (status ${abRes.status}); branch left in place but inbox may be incomplete`);
    }

    const votePath = join(paths.inboxCurrent, "VOTE.md");
    if (!existsSync(votePath)) {
      writeFileSync(votePath,
        `# Vote\n\nCompare A.pdf and B.pdf side by side. Write your choice on the line below: one of \`A\`, \`B\`, or \`tie\`. Daemon will detect the edit and merge/discard automatically.\n\n` +
        `choice: \n`
      );
    }

    console.error(`[reflect_harness] done. Inbox pending at ${paths.inboxCurrent}`);
  },
);

if (result.status === "lock_conflict") {
  console.error("[reflect_harness] inbox locked — abort deep review");
  process.exit(0);
}
